### ISSUE TITLE
In-class exercise - RMarkdown practice

### ISSUE THREAD

**Issue by cyouh95** [anyone-can-cook/rclass1#12]
Activity involving Rmarkdown practice.

**Comment by ozanj** [comment]
@cyouh95 @mpatricia01 
I'll take responsibility for the rmarkdown small group part of class. can one of you take responsibility for the "get to know each other and then pick problem set groups" part and one of you take responsibility for the "play around with using github issues and github teams to communicate and collaborate part" [that part could start w/ a brief youtube video ]
