### ISSUE TITLE
Decide on readings for next week

### ISSUE THREAD

**Issue by cyouh95** [anyone-can-cook/rclass1#16]

**Comment by cyouh95** [comment]
Readings from previous years:

- [Advanced R](https://adv-r.hadley.nz/subsetting.html) Ch. 4.1-4.4
- [R in 24 hours](http://ramanujaninstitute.com/R%20Software/R%20in%2024%20Hours.pdf) (Ch. 4 "Multi-Mode Data Structures" is the relevant section + sorting in Ch. 11)

This [cheatsheet](https://tavareshugo.github.io/data_carpentry_extras/base-r_tidyverse_equivalents/base-r_tidyverse_equivalents.html) on Base R vs. Tidyverse equivalents may also be helpful either this week or next, after we introduce Tidyverse.

**Comment by ozanj** [comment]
ENCOURAGED READING

- advanced R chapter 4.1-4.4

REQUIRED READING

- intro to R lecture, appendix section on R Markdown [I might have them read this in small groups during class tomorrow, during the RMarkdown part]
- "R for data science" chapter 27 [R markdown]
- R Markdown Definitive Guide, section 3.3, 3.4

what y'all think of this?
