### ISSUE TITLE
upload first video lecture

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#17]
Hey Patricia and Crystal

I recorded my first video lecture. Failed miserably in my goal to keep it 15 minutes or less [it was like 23 minutes]

I put the video lectures in a dropbox that I just invited you to.

I also created a short script associated w/ the video lecture that I pushed here:

rclass1\lectures\patterns_base_r\base_r_week1_video_lecture_script.R

can you please put both the video lecture and the script on the rclass1 website?

note that the video is saved as a .mkv file. I'm not sure if that is a file that everyone will be able to run on their computer. can you investigate this and if it seems like some will not be able to play it can you create a version in a more common file type?

thank you!

**Comment by cyouh95** [comment]
Added! I was able to watch the video online (on Dropbox.com) w/o any problems, so I think video format won't be an issue since we don't need to download it
