### ISSUE TITLE
in base R lecture, add a couple more examples of subset data frames by combining [] and $

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#18]
cc: @mpatricia01 

Crystal - on around slide 74 or base R lecture I added a blank slide where I'd like you to add just 2-3 more examples of subsetting data frames by combining [] and $.

can use some of the operators introduced in previous slide and/or variables that we haven't used yet

**Comment by cyouh95** [comment]
Added the following examples:

- Count the number of out-of-state high schools that UC Berkeley visited.

  ```r
  nrow(df_school[df_school$visits_by_110635 >= 1 &
                   df_school$state_code != df_school$inst_110635, ])
  ```

- Count the number of schools in the Northeast that received a visit from either UC Berkeley, U of Alabama, or CU Boulder.

  ```r
  northeast_states <- c('CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA')

  nrow(df_school[df_school$state_code %in% northeast_states &
                   (df_school$visits_by_110635 >= 1 |
                      df_school$visits_by_100751 >= 1 |
                      df_school$visits_by_126614 >= 1), ])
  ```

**Comment by ozanj** [comment]
cool. for the first one, give them a sense of what is in that variable inst_110635 before they use it to subset.

**Comment by cyouh95** [comment]
Updated!
