### ISSUE TITLE
in enter the tidyverse lecture, in filter() section add examples using subect() and also using "[] combined with $"

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#19]
cc @mpatricia01 

Crystal - in the section on filter() of the enter_the_tidyverse.Rmd lecture:

- There are a bunch of examples of using filter() to isolate desired observations
- For these examples can you also add code that:
  - does the same thing using subset operators approach of combining `[]` and `$`
  - does same thing using the base R `subset()` function

This will be helpful for the problem set.

I'm thinking that for one or two slides you would actually run this code [you'll have to add new slide breaks perhaps]

for other slides, just put the code in comments along with a note like `# same result using [] combined with $`

I don't think you have to add these lines of code for every filter() example; just do as many as you think would be helpful for students

Thanks!

**Comment by cyouh95** [comment]
Added base R equivalents to first 3 examples (2 of which contains output). Let me know if we need more!
