### ISSUE TITLE
Directory structure for R class

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#2]
pushed draft changes to intro_to_r.rmd lecture

I put several items in an "appendix", including "directories and filepaths"; "create R project and directory structure"; and "R Markdown"

Can you decide how you want to revise the "create R project and directory structure" part?

for instance, do we want students to create an R project for this class? [probably]

do we want students to download specific directory structure for the R class? probably? if so, can you two change the directory structure rclass.zip that students download?

**Comment by cyouh95** [comment]
Modified the `rclass1.zip` to reflect our new lectures folders (e.g., `intro_to_r` instead of `lecture_1`) and updated the Appendix section.
