### ISSUE TITLE
revise PS6 (due 11/13/2020)

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#31]
cc: @cyouh95 @mpatricia01 

can one of you assign yourself as lead for this?

problem set 6 will be due 11/13/2020 and will be based on the lecture about strings, dates/times

PS6 will be based on PS5 from rclass2 (winter 2020). 

I copied the files from the rclass2_dev repo into our dropbox folder rclass1_ps/problemset6

most substantive change to problem set

- prior to "part II" we should add a new a section "part I: working w/ strings" [can call it something different] that has students get a substantial amount of practice using `str_c` function and a bit of practice using `str_length` and `str_sub` 
  - basic goal is for students to __really__ understand str_c, because we use this all the time. I think where students will have difficulty is understanding the difference between two or more input vectors vs. elements of the same vector. and how the `sep` and `collapse` commands differ when there is multiple input vectors vs. one input vector etc. I forget this stuff myself.
  - variables are single atomic vectors w/ multiple elements. want students to understand that connection.
  - for the examples, mostly should just create atomic vectors w/ a few elements and then use those as inputs.
  - maybe last couple of questions should use string variables from a dataframe

Other changes that should be made

- eliminate "i got issues" github question
- note that for rclass2 students submitted scripts; but for rclass1 we will want students to submit .Rmd file
- eliminate "part I: command line & organizing project/script section"
- the section "part II: working with strings" has students stream tweets from CNN/Fox/Univision. this section should stay largely the same
- for the questions about working w/ dates/times, note that problem set from rclass2 asked students to create dataset from handles associated with the cost of living (COLA) handles. these handles don't have many recent tweets so we should either give students link to dataset we created back in the day or maybe choose different handles

**Comment by cyouh95** [comment]
I can do it this week.
