### ISSUE TITLE
revise strings_dates_time lecture

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#32]
cc: @cyouh95 @mpatricia01 

I assigned myself to this task. in addition, could one of you assign yourself too? my concern is cuz my kids are sick and not sure when I'll be able to work on this.

I created a new directory lectures/strings_dates_time and copied relevant sections of our strings lecture from rclass2

revisions to be made:

- can we put the section on  "special characters" at the end of the string section? this section is way more confusing than learning the basic string functions, so don't want students to get so discouraged right away. should we cut it entirely? not sure if that would undermine student ability to do important/basic shit they need for problem set
- can we add more detail and more intuitive explanation w/ respect to `str_c` function?
  - basic goal is for students to really understand str_c, because we use this all the time. I think where students will have difficulty is understanding the difference between two or more input vectors vs. elements of the same vector. and how the sep and collapse commands differ when there is multiple input vectors vs. one input vector etc. I forget this stuff myself.
variables are single atomic vectors w/ multiple elements. want students to understand that connection.
  - I started adding some code chunks to play around w/ this stuff but didn't get very far
- other revisions we should make? [keep updated]

**Comment by ozanj** [comment]
@cyouh95 

string/dates lecture revisions look great! thank you!

the changes to `str_c()` are fabulous!!!

a large number of very small things:

- section 2.3 converting between types is great! after the examples you currently have, can you add one short example where you use one of those functions to solve some practical data management challenge (the sort of stuff we run into in everyday work)
- in appendix 6.1 we define an "escape sequence". can you give a one-sentence definition of what a special character is right before the "common special characters"?
- in section 4.2 `str_c()`. at some point can you define what you mean by "element wise" and give a concrete example of what this means.
  - can you add a line of code that applies the `length()` function to this bit of code `str_c(c("a", "b", "c"), sep = "~")` and interpret what this means
  - add a line that applies the `length()` function to this bit of code: `str_c(c("a", "b", "c"), collapse = "|")`
    - if you want you could also show `str_length()` just to show how it differs from `length()`
  - a little bit later on, add lines that add a `length()` function to these bits of code:
    - `str_c(c("a", "b", "c"), c("x", "y", "z"), c("!", "?", ";"), sep = "~")` like this: `str_c(c("a", "b", "c"), c("x", "y", "z"), c("!", "?", ";"), collapse = "|") %>% length()`
    - `str_c(c("a", "b", "c"), c("x", "y", "z"), c("!", "?", ";"), collapse = "|")`
- in the example "using str_c() on strings"
  - can you define what you mean by "strings"? is this the right term? I am not sure if "string" by definition means of a character atomic vector of length()==1. I thought strings could have any number of elements. just make sure.
- in that same example, maybe add a line showing that these two are the same:
  - `str_c("a", "b", "c")`
  - str_c(c("a"), c("b"), c("c"))

Thank you!!!!

**Comment by cyouh95** [comment]
Made these changes! A couple notes:

- The converting type example I added is related to labeling values in a dataframe. Not sure if this is the best example, but I couldn't really think of anything else. I know labeling hasn't been introduced yet, but hopefully the explanation is clear enough.
- I think strings are just anything you put in between quotes. According to [here](https://stackoverflow.com/questions/18513200/what-is-the-difference-between-string-and-character-in-r), strings aren't an actual type in R, but by the definition of strings as being anything surrounded by quotes, we could loosely refer to elements of a character vector as being strings. A string definitely isn't "defined" as a character vector of length 1, but I just mean it can be helpful to think of it as such, since `"a"` is treated similarly as `c("a")` when inputted to `str_c()` - maybe we can reword if that sounds too misleading?

**Comment by ozanj** [comment]
Thank you Crystal!

on your second point:

How you are using "string" is consistent w/ how I think of it. I just added some of your wording from above bullet to the lecture. and just pushed.

you did a fabulous job improving the lecture. the students will benefit greatly from this!
