### ISSUE TITLE
deleting student repos from previous quarters

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#34]
@cyouh95 @lizachavac @briannawright135 

Brianna Liza - I'd like one of you to take the lead in cleaning up the "anyone can cook" github organization. basically, we have dozens of repos from previous quarters that should be deleted [and probably "teams" from previous quarters that should be deleted.

For the repos - For each class that had repos (should be able to figure this out from teams and/or repo names), can you send an announcement to the class saying that repos will be deleted in one week and they should save everything they need. and then delete in one week. 

Feel free to ask @cyouh95 for advice on best way to do this. and either @lizachavac or @briannawright135 - please assign the task to yourself.

thx!

**Comment by briannawright135** [comment]
Sounds good. I changed previous teams to a “secret” status so that only
members of the team can see them. Should I go ahead and just delete them in
a week after sending an announcement instead of “secret” status?

Brianna

**Comment by ozanj** [comment]
ah. cool. I didn't realize the "secret" status thing.

but yeah let's go ahead w/ deleting them after giving students a week. it'll make things easier for us to navigate. thx!
