### ISSUE TITLE
questions related to Problem Set 1

### ISSUE THREAD

**Issue by jstrau06** [anyone-can-cook/rclass1#36]
I am having issues with Questions 5 and 6, where I keep getting this error message:

[1] "/Users/jolie/Documents/rclass1"
> #load data without setting directory
> load("../data/recruiting/recruit_ps1_small.Rdata")

"cannot open compressed file '../data/recruiting/recruit_ps1_small.Rdata', probable reason 'No such file or directory'Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection"
@ozanj @lizachavac @briannawright135

**Comment by lizachavac** [comment]
@jstrau06 for the code load("data.Rdata") we are looking to input the data file only in the data part of the code. So the code should look like load("recruit_ps1_small.Rdata"). Let me know if that helps!

**Comment by jstrau06** [comment]
thank you Liza! Brianna talked me through this in OH. I appreciate your help as well!
