### ISSUE TITLE
Tick marks in figures

### ISSUE THREAD

**Issue by ilanabrody** [anyone-can-cook/rclass1#38]
Does anyone know how to add tick marks to the end of confidence intervals in figures in R, if they do not appear by default?

@lizachavac @briannawright135 @wdoyle42

**Comment by briannawright135** [comment]
This may be different on a PC but on my Mac I can insert tick marks from my keyboard. The key is at the top left of the keyboard on the same key as the tilde OR I just copy a tick mark from a code chunk.
