### ISSUE TITLE
Problem Set 1 Formatting Question

### ISSUE THREAD

**Issue by ecedwards01** [anyone-can-cook/rclass1#39]
Hi! There were a few questions embedded within the action items of this week's problem set. For future reference, is there a particular way that you would prefer for our responses be formatted or organized? @lizachavac @briannawright135. Also, @creciendo is my classmate mention :)

**Comment by lizachavac** [comment]
@ecedwards01 are you referring to the questions in 1 and 2? Like what is the output and why? I believe those are questions that we want you to keep in mind. However, I will double-check to make sure.

**Comment by ecedwards01** [comment]
@lizachavac Yes, Im referring to those questions. Oops, I didn't realize they were rhetorical questions! haha. Ok yes, please me posted. Thanks!
