### ISSUE TITLE
Code Chunks

### ISSUE THREAD

**Issue by karolynmaurer** [anyone-can-cook/rclass1#41]
What is the purpose of a code chunk? Do you suggest we create a new code chunk every time we run any new code? 
@briannawright135 @lizachavac @rmklinkel

**Comment by briannawright135** [comment]
@karolynmaurer You don't need to create a new code chunk- they will be included in the problem set files when you download them. The code chunks are helpful because we can write text in our .rmd file, write code in the chunks, and then see the output right below the code chunk.
