### ISSUE TITLE
Che NAM

### ISSUE THREAD

**Issue by NadiaSabatBass** [anyone-can-cook/rclass1#52]
@anyone-can-cook/che-nam We need to find a good group picture :)

**Comment by marlenesaintma** [comment]
I'm going to google what comes up when you search Che NAM...

**Comment by marlenesaintma** [comment]
So, this comes up, not sure if that is what we are going for though lol 

![image](https://user-images.githubusercontent.com/90576511/135665084-6b44fcf0-9f39-4b62-995b-179c0fb97cda.png)

**Comment by amanda-carrasco** [comment]
Haha not sure what it is but I don't see why not lol
