### ISSUE TITLE
course website

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#56]
Hey Liza and Brianna,

can one of you add the video lectures that I did in synchronous class today to the lectures by topic section of the course website? in addition, the name/description of the video should start w/ the section numbers, e.g. `1.3`

also, under "weekly readings and assignments" there is this, that goes to nowhere and should probably be deleted

"Lecture video for Week 1 (10/01/21) - Investigating data patterns in Base R"

**Comment by briannawright135** [comment]
@ozanj I uploaded the videos and put them on the website. Are you able to see them? I can on my end when I visit the site. 

-I will rename the videos in the morning so that they include the section numbers from the lecture slides

-I can also delete the "Lecture Video for Week 1..."

**Comment by lizachavac** [comment]
@ozanj @briannawright135 oops I went ahead and fixed it! let me know if that's what you meant Ozan

**Comment by ozanj** [comment]
I see videos now up. Thank u!
