### ISSUE TITLE
Problem set#2 What I learned 

### ISSUE THREAD

**Issue by lyenna668** [anyone-can-cook/rclass1#58]
I learned how to add a table of content and how to knit to PDF when the output runs large. 
I was also able to practice functions like str(), typeof(), table(),and return to a specific element/column. The most rewarding moment is when I finally understand the codes and function conceptually. :)  Thanks @briannawright135 @lizachavac and my @anyone-can-cook/fabulous-6 team.

@ozanj @briannawright135 @lizachavac @anyone-can-cook/fabulous-6

**Comment by JesseeEspinosa** [comment]
I totally agree that it is really rewarding when you are struggling to get something to work and you finally do it! This class is challenging more than my prior classes, but it is also unique in teaching me to overcome obstacles as well. Glad to see the same for you.
