### ISSUE TITLE
modify vertical space on beamer lecture slides

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#6]
copy @mpatricia01 

editing intro_to_r.rmd lecture

bullet points look too compact.

Crystal - can you try to modify vertical spacing between bullets [and any other aspect of vertical spacing that you think would improve the look of the slides]

This may involve editing the rclass1/lectures/beamer_header.tex file. in the past we commented out some lines because of problems w/ tinytex/miktex. maybe that can be changed now?? i dunno.

**Comment by cyouh95** [comment]
I tried uncommenting the lines but don't think it made a difference. I think the issue was related to us using newer versions of R now, since I think the issue started after we updated R a couple years ago. So it might not be compatible anymore? But I can look into it more.

**Comment by ozanj** [comment]
let's just forget about it!
