### ISSUE TITLE
problem set #3 Q1 error message with _tidyverse using `filter()`__:

### ISSUE THREAD

**Issue by lyenna668** [anyone-can-cook/rclass1#60]
Q1: By the University of Massachusetts-Amherst (`univ_id`: `166629`)
    - An out-of-state public high school (use `event_type`, `event_state`, and `instst`, which is the visiting university's home state)
    
  I used the code chunks: 
nrow(filter(df_event, visits_by_166629 == 1, event_type =="public", event_state != "CA", instst != "CA"))
I keep receiving error message: 
Error: Problem with `filter()` input `..1`.
ℹ Input `..1` is `visits_by_166629 == 1`.
x object 'visits_by_166629' not found

Can anyone help? @ozanj @briannawright135 @lizachavac @anyone-can-cook/fabulous-6  Thank you!

**Comment by henry-r18** [comment]
@lyenna668 Question 2 is basically asking for a summary of recruiting events by a university in Massachusetts, so the filter() should return visits that are out-of-state of MA, rather than CA. It's out-of-state relative to the visiting institution, I believe. That got me at first too!
