### ISSUE TITLE
Question for PS #3: Error when reopening .rmd file

### ISSUE THREAD

**Issue by henry-r18** [anyone-can-cook/rclass1#61]
When I close RStudio, then reopen it, it seems like tidyverse keeps uninstalling. One of my teammates pointed out the package manager in the bottom right window under the tab 'Packages,' so I checked tidyverse there. That seems to work, but is there a way to tell R to install packages globally, other than the package manager? @ozanj, @lizachavac, @briannawright135 @anyone-can-cook/thundercats

**Comment by briannawright135** [comment]
@henry-r18 You only need to install tidyverse once and you do it in the console. Can you try doing `library(tidyverse)`in your .Rmd and see if RStudio gives you an error? All this does is call or tell R you are going to use this package as you work.
