### ISSUE TITLE
did i do this

### ISSUE THREAD

**Issue by miacarbone** [anyone-can-cook/rclass1#64]
i can't tell if this is going to work lol

**Comment by tyrus-korecki** [comment]
It worked!

**Comment by augias** [comment]
@tyrus-korecki @miacarbone  I think you took a wrong turn! this is the rclass1 base github repository for website and lecture materials. Wlecome!, However, we'll be using https://github.com/anyone-can-cook/rclass1_student_issues_f22/issues as the repo for discussions and issues!

**Comment by miacarbone** [comment]
i figured it out and posted in the other a few minutes ago! thanks @augias :)

**Comment by augias** [comment]
@miacarbone one last homework assignment! If you're done with this issue try closing this issue
