### ISSUE TITLE
add link to class website to top of syllabus

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass1#7]
cc: @cyouh95 

add link to class website [and spell out url] at top of syllabus

**Comment by mpatricia01** [comment]
Do you want me to move the class website section or leave that as is, but add the class website at the top of syllabus?

**Comment by mpatricia01** [comment]
![Screen Shot 2020-09-30 at 3 15 40 PM](https://user-images.githubusercontent.com/33170829/94745586-db265200-032f-11eb-8952-22ec19ab2e3e.png)

Does this work okay? I added this below Course description.

**Comment by ozanj** [comment]
love it!

and yes, keep the class website section where it is. just want students to be able to see stuff like website, zoom link etc. right at top of website for quick reference
