### ISSUE TITLE
Problem Set #1

### ISSUE THREAD

**Issue by samuelnewman03** [anyone-can-cook/rclass1#70]
@augias 

Hi! I am having problems opening problem set #1. Do I have to wait until Monday for it to be released?

**Comment by augias** [comment]
@samuelnewman03 It is released and available on box for anyone with the link. Please explain in a little more detail what the problem is exactly. 

You *should* be prompted to log onto Box with your UCLA credentials. Then a page with the option to download the Rmd document will appear, and you can download it and move it to a class folder

**Comment by samuelnewman03** [comment]
When I click on the link, I see the following message: "This shared file or folder link has been removed or is unavailable to you."

I didn't receive the general email that was sent out either. Not sure if the problems are connected. I tried to attach a screenshot below. 

[image](https://user-images.githubusercontent.com/114192107/192035707-26990ed8-0623-423a-af67-c9eed8869986.png)

**Comment by augias** [comment]
This suggests that you are not logged on, or not getting prompted to log on to Box.

The sharing conditions are for 'people in your company', meaning people with a ucla.box.com account. If you haven't yet, please try logging in to ucla.box.com with your ucla credentials and see if you gain access that way. Let me know if that helps.

@ozanj do I have permission to change problemset url access from 'people in the company' to 'anyone with the link', if this doesn't solve it?

**Comment by ozanj** [comment]
@augias - yes on changing permissions to anyone with the link.

in fact, for all resources on the course website (except for the class discussion) I want it to be open to anyone in the world.

@augias - can you create a separate github issue for this?

**Comment by samuelnewman03** [comment]
@augias I am able to login to UCLA.box.com, but having the same issue when I try open the problem set.

**Comment by augias** [comment]
bet. @samuelnewman03 i just opened problemset1 links to anyone. If this worked, please let us know and/or close this issue!

**Comment by samuelnewman03** [comment]
@augias I'm in! Thanks so much for the help. It feels meta that posting an issue was also a HW question lol. Thanks again!

**Comment by ozanj** [comment]
ha @samuelnewman03 ! it'll get less meta once we get all of these beginning-of-quarter bugs worked out (I think!)
