### ISSUE TITLE
Question 5 in PS1: What is your favorite memory from the last year?

### ISSUE THREAD

**Issue by lucybriggs12** [anyone-can-cook/rclass1#73]
What is your favorite memory from the last year? 
@xochilthlopez, @RachelBerwald, @joycehnguy, @augias, @BlockJared

**Comment by augias** [comment]
@lucybriggs12 I think you got turned around on your way around the class site! Perfectly understandable. However, we set up a different repository for discussions and issues for 260A. It's over here: https://github.com/anyone-can-cook/rclass1_student_issues_f22/issues

Don't worry about it for this week though!

We use this specific repository for troubleshooting the course site between ozan and the TAs.
