### ISSUE TITLE
Difference between lists and vectors?

### ISSUE THREAD

**Issue by ahariharan014** [anyone-can-cook/rclass1#77]
Hey all,

I'm working on question 2.2 of PS2 with my group and it's becoming clear to me that I don't understand the difference between lists and vectors. Am I correct in thinking that dataframes are lists of elements (variables) and the contents of the variables are stored in vectors?  @ozanj @joycehnguy @rachelberwald @xochilthlopez @anyone-can-cook/the-rat-from-ratatouille-was-my-first-crush

**Comment by enortiz321** [comment]
Yeah I am also confused about this distinction. Is it just that lists can contain different data types at the same time and a vector cannot, or is there something more to it?
