### ISSUE TITLE
Using vector[c()] when subsetting vectors

### ISSUE THREAD

**Issue by and-rock** [anyone-can-cook/rclass1#80]
When calling R to return multiple elements of an atomic vector, can someone explain again why we need to nest a vector with the numbers (or names) of the elements we want to call? For example, why do we have to write vec[c(4, 7)] rather than just vec[4, 7]? Thanks!

@ozanj @xochilthlopez @rachelberwald @joycehnguy @augias @anyone-can-cook/the-room

**Comment by tyrus-korecki** [comment]
Hi @and-rock , I am not an expert in any of this, so please take my answer with a grain of salt. My understanding is that R is expecting only one vector inside of the "[ ]" and the use of a "," is breaking that rule by putting two separate vectors in the "[]", so there is no output. Using "c()" is creating a single vector even though you are asking for two separate elements of your atomic vector. The reason you can use ":" to request a sequence of numbers (i.e., numbers next to one another in a row) is that the ":" is creating a single vector, thus satisfying R's requirement of a single vector inside of the "[]"  I hope this helps!

Tyrus
